### ISSUE TITLE
Primefaces 8.0 compatibility

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [illucIT/primefaces-imageeditor#3]
check if it is compatible

**Comment by metaxmx** [comment]
Hi,
I checked it against the new PrimeFaces version, and it is not compatible, because the internal API about file uploading has changed slightly.

So I published a new Version 2.2.0, which is compatible with PrimeFaces 8.0.

In order to use the new version, just update your dependency:

```xml
	<dependency>
		<groupId>com.illucit</groupId>
		<artifactId>primefaces-imageeditor</artifactId>
		<version>2.2.0</version>
	</dependency>
```

Please let me know, if you still find some problems with PrimeFaces 8.0
